# Generated by Django 5.1.7 on 2025-03-31 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sezione', models.CharField(max_length=80)),
                ('descrizione', models.CharField(blank=True, max_length=150, null=True)),
                ('logo_sezione', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Sezione',
                'verbose_name_plural': 'Sezioni',
            },
        ),
        migrations.CreateModel(
            name='Discussione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=120)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('autore_discussione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussioni', to=settings.AUTH_USER_MODEL)),
                ('sezione_appartenenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sezione')),
            ],
            options={
                'verbose_name': 'Discussione',
                'verbose_name_plural': 'Discussioni',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('autore_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('discussione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discussione')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
